//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//


package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}COMPLIANCE_TYPE"/>
 *         &lt;element ref="{}COMPLIANCE_SECTION"/>
 *         &lt;element ref="{}COMPLIANCE_DESCRIPTION"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "compliancetype",
    "compliancesection",
    "compliancedescription"
})
@XmlRootElement(name = "COMPLIANCE_INFO")
public class COMPLIANCEINFO {

    @XmlElement(name = "COMPLIANCE_TYPE", required = true)
    protected String compliancetype;
    @XmlElement(name = "COMPLIANCE_SECTION", required = true)
    protected String compliancesection;
    @XmlElement(name = "COMPLIANCE_DESCRIPTION", required = true)
    protected String compliancedescription;

    /**
     * Gets the value of the compliancetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPLIANCETYPE() {
        return compliancetype;
    }

    /**
     * Sets the value of the compliancetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPLIANCETYPE(String value) {
        this.compliancetype = value;
    }

    /**
     * Gets the value of the compliancesection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPLIANCESECTION() {
        return compliancesection;
    }

    /**
     * Sets the value of the compliancesection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPLIANCESECTION(String value) {
        this.compliancesection = value;
    }

    /**
     * Gets the value of the compliancedescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPLIANCEDESCRIPTION() {
        return compliancedescription;
    }

    /**
     * Sets the value of the compliancedescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPLIANCEDESCRIPTION(String value) {
        this.compliancedescription = value;
    }

}
