//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//


package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CVSS_BASE" minOccurs="0"/>
 *         &lt;element ref="{}CVSS_TEMPORAL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cvssbase",
    "cvsstemporal"
})
@XmlRootElement(name = "CVSS_SCORE")
public class CVSSSCORE {

    @XmlElement(name = "CVSS_BASE")
    protected CVSSBASE cvssbase;
    @XmlElement(name = "CVSS_TEMPORAL")
    protected String cvsstemporal;

    /**
     * Gets the value of the cvssbase property.
     * 
     * @return
     *     possible object is
     *     {@link CVSSBASE }
     *     
     */
    public CVSSBASE getCVSSBASE() {
        return cvssbase;
    }

    /**
     * Sets the value of the cvssbase property.
     * 
     * @param value
     *     allowed object is
     *     {@link CVSSBASE }
     *     
     */
    public void setCVSSBASE(CVSSBASE value) {
        this.cvssbase = value;
    }

    /**
     * Gets the value of the cvsstemporal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVSSTEMPORAL() {
        return cvsstemporal;
    }

    /**
     * Sets the value of the cvsstemporal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVSSTEMPORAL(String value) {
        this.cvsstemporal = value;
    }

}
