//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//


package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SRC_NAME"/>
 *         &lt;element ref="{}EXPLT_LIST"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "srcname",
    "expltlist"
})
@XmlRootElement(name = "EXPLT_SRC")
public class EXPLTSRC {

    @XmlElement(name = "SRC_NAME", required = true)
    protected String srcname;
    @XmlElement(name = "EXPLT_LIST", required = true)
    protected EXPLTLIST expltlist;

    /**
     * Gets the value of the srcname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSRCNAME() {
        return srcname;
    }

    /**
     * Sets the value of the srcname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSRCNAME(String value) {
        this.srcname = value;
    }

    /**
     * Gets the value of the expltlist property.
     * 
     * @return
     *     possible object is
     *     {@link EXPLTLIST }
     *     
     */
    public EXPLTLIST getEXPLTLIST() {
        return expltlist;
    }

    /**
     * Sets the value of the expltlist property.
     * 
     * @param value
     *     allowed object is
     *     {@link EXPLTLIST }
     *     
     */
    public void setEXPLTLIST(EXPLTLIST value) {
        this.expltlist = value;
    }

}
