//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//


package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}COMPANY"/>
 *         &lt;element ref="{}USERNAME"/>
 *         &lt;element ref="{}GENERATION_DATETIME"/>
 *         &lt;element ref="{}TEMPLATE"/>
 *         &lt;element ref="{}TARGET"/>
 *         &lt;element ref="{}RISK_SCORE_SUMMARY" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "company",
    "username",
    "generationdatetime",
    "template",
    "target",
    "riskscoresummary"
})
@XmlRootElement(name = "HEADER")
public class HEADER {

    @XmlElement(name = "COMPANY", required = true)
    protected String company;
    @XmlElement(name = "USERNAME", required = true)
    protected String username;
    @XmlElement(name = "GENERATION_DATETIME", required = true)
    protected String generationdatetime;
    @XmlElement(name = "TEMPLATE", required = true)
    protected String template;
    @XmlElement(name = "TARGET", required = true)
    protected TARGET target;
    @XmlElement(name = "RISK_SCORE_SUMMARY")
    protected RISKSCORESUMMARY riskscoresummary;

    /**
     * Gets the value of the company property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPANY() {
        return company;
    }

    /**
     * Sets the value of the company property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPANY(String value) {
        this.company = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSERNAME() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSERNAME(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the generationdatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENERATIONDATETIME() {
        return generationdatetime;
    }

    /**
     * Sets the value of the generationdatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENERATIONDATETIME(String value) {
        this.generationdatetime = value;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTEMPLATE() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTEMPLATE(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link TARGET }
     *     
     */
    public TARGET getTARGET() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link TARGET }
     *     
     */
    public void setTARGET(TARGET value) {
        this.target = value;
    }

    /**
     * Gets the value of the riskscoresummary property.
     * 
     * @return
     *     possible object is
     *     {@link RISKSCORESUMMARY }
     *     
     */
    public RISKSCORESUMMARY getRISKSCORESUMMARY() {
        return riskscoresummary;
    }

    /**
     * Sets the value of the riskscoresummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link RISKSCORESUMMARY }
     *     
     */
    public void setRISKSCORESUMMARY(RISKSCORESUMMARY value) {
        this.riskscoresummary = value;
    }

}
