//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//


package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}ERROR"/>
 *         &lt;sequence>
 *           &lt;element ref="{}IP"/>
 *           &lt;element ref="{}TRACKING_METHOD"/>
 *           &lt;element ref="{}ASSET_TAGS" minOccurs="0"/>
 *           &lt;element ref="{}DNS" minOccurs="0"/>
 *           &lt;element ref="{}NETBIOS" minOccurs="0"/>
 *           &lt;element ref="{}OPERATING_SYSTEM" minOccurs="0"/>
 *           &lt;element ref="{}OS_CPE" minOccurs="0"/>
 *           &lt;element ref="{}ASSET_GROUPS" minOccurs="0"/>
 *           &lt;element ref="{}VULN_INFO_LIST" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "error",
    "ip",
    "trackingmethod",
    "assettags",
    "dns",
    "netbios",
    "operatingsystem",
    "oscpe",
    "assetgroups",
    "vulninfolist"
})
@XmlRootElement(name = "HOST")
public class HOST {

    @XmlElement(name = "ERROR")
    protected ERROR error;
    @XmlElement(name = "IP")
    protected IP ip;
    @XmlElement(name = "TRACKING_METHOD")
    protected String trackingmethod;
    @XmlElement(name = "ASSET_TAGS")
    protected ASSETTAGS assettags;
    @XmlElement(name = "DNS")
    protected String dns;
    @XmlElement(name = "NETBIOS")
    protected String netbios;
    @XmlElement(name = "OPERATING_SYSTEM")
    protected String operatingsystem;
    @XmlElement(name = "OS_CPE")
    protected String oscpe;
    @XmlElement(name = "ASSET_GROUPS")
    protected ASSETGROUPS assetgroups;
    @XmlElement(name = "VULN_INFO_LIST")
    protected VULNINFOLIST vulninfolist;

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ERROR }
     *     
     */
    public ERROR getERROR() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ERROR }
     *     
     */
    public void setERROR(ERROR value) {
        this.error = value;
    }

    /**
     * Gets the value of the ip property.
     * 
     * @return
     *     possible object is
     *     {@link IP }
     *     
     */
    public IP getIP() {
        return ip;
    }

    /**
     * Sets the value of the ip property.
     * 
     * @param value
     *     allowed object is
     *     {@link IP }
     *     
     */
    public void setIP(IP value) {
        this.ip = value;
    }

    /**
     * Gets the value of the trackingmethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRACKINGMETHOD() {
        return trackingmethod;
    }

    /**
     * Sets the value of the trackingmethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRACKINGMETHOD(String value) {
        this.trackingmethod = value;
    }

    /**
     * Gets the value of the assettags property.
     * 
     * @return
     *     possible object is
     *     {@link ASSETTAGS }
     *     
     */
    public ASSETTAGS getASSETTAGS() {
        return assettags;
    }

    /**
     * Sets the value of the assettags property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASSETTAGS }
     *     
     */
    public void setASSETTAGS(ASSETTAGS value) {
        this.assettags = value;
    }

    /**
     * Gets the value of the dns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNS() {
        return dns;
    }

    /**
     * Sets the value of the dns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNS(String value) {
        this.dns = value;
    }

    /**
     * Gets the value of the netbios property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETBIOS() {
        return netbios;
    }

    /**
     * Sets the value of the netbios property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETBIOS(String value) {
        this.netbios = value;
    }

    /**
     * Gets the value of the operatingsystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOPERATINGSYSTEM() {
        return operatingsystem;
    }

    /**
     * Sets the value of the operatingsystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOPERATINGSYSTEM(String value) {
        this.operatingsystem = value;
    }

    /**
     * Gets the value of the oscpe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOSCPE() {
        return oscpe;
    }

    /**
     * Sets the value of the oscpe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOSCPE(String value) {
        this.oscpe = value;
    }

    /**
     * Gets the value of the assetgroups property.
     * 
     * @return
     *     possible object is
     *     {@link ASSETGROUPS }
     *     
     */
    public ASSETGROUPS getASSETGROUPS() {
        return assetgroups;
    }

    /**
     * Sets the value of the assetgroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link ASSETGROUPS }
     *     
     */
    public void setASSETGROUPS(ASSETGROUPS value) {
        this.assetgroups = value;
    }

    /**
     * Gets the value of the vulninfolist property.
     * 
     * @return
     *     possible object is
     *     {@link VULNINFOLIST }
     *     
     */
    public VULNINFOLIST getVULNINFOLIST() {
        return vulninfolist;
    }

    /**
     * Sets the value of the vulninfolist property.
     * 
     * @param value
     *     allowed object is
     *     {@link VULNINFOLIST }
     *     
     */
    public void setVULNINFOLIST(VULNINFOLIST value) {
        this.vulninfolist = value;
    }

}
