//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//


package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}MW_ID"/>
 *         &lt;element ref="{}MW_TYPE" minOccurs="0"/>
 *         &lt;element ref="{}MW_PLATFORM" minOccurs="0"/>
 *         &lt;element ref="{}MW_ALIAS" minOccurs="0"/>
 *         &lt;element ref="{}MW_RATING" minOccurs="0"/>
 *         &lt;element ref="{}MW_LINK" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mwid",
    "mwtype",
    "mwplatform",
    "mwalias",
    "mwrating",
    "mwlink"
})
@XmlRootElement(name = "MW_INFO")
public class MWINFO {

    @XmlElement(name = "MW_ID", required = true)
    protected String mwid;
    @XmlElement(name = "MW_TYPE")
    protected String mwtype;
    @XmlElement(name = "MW_PLATFORM")
    protected String mwplatform;
    @XmlElement(name = "MW_ALIAS")
    protected String mwalias;
    @XmlElement(name = "MW_RATING")
    protected String mwrating;
    @XmlElement(name = "MW_LINK")
    protected String mwlink;

    /**
     * Gets the value of the mwid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMWID() {
        return mwid;
    }

    /**
     * Sets the value of the mwid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMWID(String value) {
        this.mwid = value;
    }

    /**
     * Gets the value of the mwtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMWTYPE() {
        return mwtype;
    }

    /**
     * Sets the value of the mwtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMWTYPE(String value) {
        this.mwtype = value;
    }

    /**
     * Gets the value of the mwplatform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMWPLATFORM() {
        return mwplatform;
    }

    /**
     * Sets the value of the mwplatform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMWPLATFORM(String value) {
        this.mwplatform = value;
    }

    /**
     * Gets the value of the mwalias property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMWALIAS() {
        return mwalias;
    }

    /**
     * Sets the value of the mwalias property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMWALIAS(String value) {
        this.mwalias = value;
    }

    /**
     * Gets the value of the mwrating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMWRATING() {
        return mwrating;
    }

    /**
     * Sets the value of the mwrating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMWRATING(String value) {
        this.mwrating = value;
    }

    /**
     * Gets the value of the mwlink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMWLINK() {
        return mwlink;
    }

    /**
     * Sets the value of the mwlink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMWLINK(String value) {
        this.mwlink = value;
    }

}
