//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//


package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}IP_LIST"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iplist"
})
@XmlRootElement(name = "NO_VULNS")
public class NOVULNS {

    @XmlElement(name = "IP_LIST", required = true)
    protected IPLIST iplist;

    /**
     * Gets the value of the iplist property.
     * 
     * @return
     *     possible object is
     *     {@link IPLIST }
     *     
     */
    public IPLIST getIPLIST() {
        return iplist;
    }

    /**
     * Sets the value of the iplist property.
     * 
     * @param value
     *     allowed object is
     *     {@link IPLIST }
     *     
     */
    public void setIPLIST(IPLIST value) {
        this.iplist = value;
    }

}
