//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//


package com.qualys.audit.data;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.qualys.audit.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CUSTOMSEVERITY_QNAME = new QName("", "CUSTOM_SEVERITY");
    private final static QName _COMPLIANCESECTION_QNAME = new QName("", "COMPLIANCE_SECTION");
    private final static QName _SEVERITY_QNAME = new QName("", "SEVERITY");
    private final static QName _IMPACT_QNAME = new QName("", "IMPACT");
    private final static QName _DISABLED_QNAME = new QName("", "DISABLED");
    private final static QName _THREATCOMMENT_QNAME = new QName("", "THREAT_COMMENT");
    private final static QName _SECURITYRISK_QNAME = new QName("", "SECURITY_RISK");
    private final static QName _SRCNAME_QNAME = new QName("", "SRC_NAME");
    private final static QName _FIRSTFOUND_QNAME = new QName("", "FIRST_FOUND");
    private final static QName _OPERATINGSYSTEM_QNAME = new QName("", "OPERATING_SYSTEM");
    private final static QName _ID_QNAME = new QName("", "ID");
    private final static QName _OSCPE_QNAME = new QName("", "OS_CPE");
    private final static QName _DNS_QNAME = new QName("", "DNS");
    private final static QName _PROTOCOL_QNAME = new QName("", "PROTOCOL");
    private final static QName _TRACKINGMETHOD_QNAME = new QName("", "TRACKING_METHOD");
    private final static QName _TIMESFOUND_QNAME = new QName("", "TIMES_FOUND");
    private final static QName _CVSSTEMPORAL_QNAME = new QName("", "CVSS_TEMPORAL");
    private final static QName _FQDN_QNAME = new QName("", "FQDN");
    private final static QName _TYPE_QNAME = new QName("", "TYPE");
    private final static QName _EXCLUDEDCATEGORIES_QNAME = new QName("", "EXCLUDED_CATEGORIES");
    private final static QName _ASSETTAG_QNAME = new QName("", "ASSET_TAG");
    private final static QName _COMPANY_QNAME = new QName("", "COMPANY");
    private final static QName _SELECTIVEVULNS_QNAME = new QName("", "SELECTIVE_VULNS");
    private final static QName _COMPLIANCETYPE_QNAME = new QName("", "COMPLIANCE_TYPE");
    private final static QName _COMPLIANCEDESCRIPTION_QNAME = new QName("", "COMPLIANCE_DESCRIPTION");
    private final static QName _MWID_QNAME = new QName("", "MW_ID");
    private final static QName _EXCLUDEDVULNLISTS_QNAME = new QName("", "EXCLUDED_VULN_LISTS");
    private final static QName _MWLINK_QNAME = new QName("", "MW_LINK");
    private final static QName _LASTFOUND_QNAME = new QName("", "LAST_FOUND");
    private final static QName _USERNAME_QNAME = new QName("", "USERNAME");
    private final static QName _SOLUTIONCOMMENT_QNAME = new QName("", "SOLUTION_COMMENT");
    private final static QName _VULNLISTS_QNAME = new QName("", "VULN_LISTS");
    private final static QName _CVSSFINAL_QNAME = new QName("", "CVSS_FINAL");
    private final static QName _MWPLATFORM_QNAME = new QName("", "MW_PLATFORM");
    private final static QName _ASSETGROUPTITLE_QNAME = new QName("", "ASSET_GROUP_TITLE");
    private final static QName _RESULTINGVULNS_QNAME = new QName("", "RESULTING_VULNS");
    private final static QName _GENERATIONDATETIME_QNAME = new QName("", "GENERATION_DATETIME");
    private final static QName _CATEGORY_QNAME = new QName("", "CATEGORY");
    private final static QName _PORT_QNAME = new QName("", "PORT");
    private final static QName _THREAT_QNAME = new QName("", "THREAT");
    private final static QName _TOTALVULNERABILITIES_QNAME = new QName("", "TOTAL_VULNERABILITIES");
    private final static QName _LINK_QNAME = new QName("", "LINK");
    private final static QName _NETBIOS_QNAME = new QName("", "NETBIOS");
    private final static QName _TICKETSTATE_QNAME = new QName("", "TICKET_STATE");
    private final static QName _URL_QNAME = new QName("", "URL");
    private final static QName _REF_QNAME = new QName("", "REF");
    private final static QName _MWALIAS_QNAME = new QName("", "MW_ALIAS");
    private final static QName _TICKETNUMBER_QNAME = new QName("", "TICKET_NUMBER");
    private final static QName _LASTUPDATE_QNAME = new QName("", "LAST_UPDATE");
    private final static QName _SSL_QNAME = new QName("", "SSL");
    private final static QName _SERVICE_QNAME = new QName("", "SERVICE");
    private final static QName _SOLUTION_QNAME = new QName("", "SOLUTION");
    private final static QName _TEMPLATE_QNAME = new QName("", "TEMPLATE");
    private final static QName _MWTYPE_QNAME = new QName("", "MW_TYPE");
    private final static QName _PCIFLAG_QNAME = new QName("", "PCI_FLAG");
    private final static QName _EXCLUDEDVULNS_QNAME = new QName("", "EXCLUDED_VULNS");
    private final static QName _INSTANCE_QNAME = new QName("", "INSTANCE");
    private final static QName _VULNSTATUS_QNAME = new QName("", "VULN_STATUS");
    private final static QName _FILTERSUMMARY_QNAME = new QName("", "FILTER_SUMMARY");
    private final static QName _BUSINESSRISK_QNAME = new QName("", "BUSINESS_RISK");
    private final static QName _AVGSECURITYRISK_QNAME = new QName("", "AVG_SECURITY_RISK");
    private final static QName _START_QNAME = new QName("", "START");
    private final static QName _MWRATING_QNAME = new QName("", "MW_RATING");
    private final static QName _IMPACTCOMMENT_QNAME = new QName("", "IMPACT_COMMENT");
    private final static QName _DESC_QNAME = new QName("", "DESC");
    private final static QName _END_QNAME = new QName("", "END");
    private final static QName _TITLE_QNAME = new QName("", "TITLE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.qualys.audit.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NOVULNS }
     * 
     */
    public NOVULNS createNOVULNS() {
        return new NOVULNS();
    }

    /**
     * Create an instance of {@link IPLIST }
     * 
     */
    public IPLIST createIPLIST() {
        return new IPLIST();
    }

    /**
     * Create an instance of {@link RANGE }
     * 
     */
    public RANGE createRANGE() {
        return new RANGE();
    }

    /**
     * Create an instance of {@link TEMPLATEDETAILS }
     * 
     */
    public TEMPLATEDETAILS createTEMPLATEDETAILS() {
        return new TEMPLATEDETAILS();
    }

    /**
     * Create an instance of {@link VULNINFO }
     * 
     */
    public VULNINFO createVULNINFO() {
        return new VULNINFO();
    }

    /**
     * Create an instance of {@link QID }
     * 
     */
    public QID createQID() {
        return new QID();
    }

    /**
     * Create an instance of {@link RESULT }
     * 
     */
    public RESULT createRESULT() {
        return new RESULT();
    }

    /**
     * Create an instance of {@link BUGTRAQIDLIST }
     * 
     */
    public BUGTRAQIDLIST createBUGTRAQIDLIST() {
        return new BUGTRAQIDLIST();
    }

    /**
     * Create an instance of {@link BUGTRAQID }
     * 
     */
    public BUGTRAQID createBUGTRAQID() {
        return new BUGTRAQID();
    }

    /**
     * Create an instance of {@link INCLUDEDTAGS }
     * 
     */
    public INCLUDEDTAGS createINCLUDEDTAGS() {
        return new INCLUDEDTAGS();
    }

    /**
     * Create an instance of {@link HOSTLIST }
     * 
     */
    public HOSTLIST createHOSTLIST() {
        return new HOSTLIST();
    }

    /**
     * Create an instance of {@link HOST }
     * 
     */
    public HOST createHOST() {
        return new HOST();
    }

    /**
     * Create an instance of {@link ERROR }
     * 
     */
    public ERROR createERROR() {
        return new ERROR();
    }

    /**
     * Create an instance of {@link IP }
     * 
     */
    public IP createIP() {
        return new IP();
    }

    /**
     * Create an instance of {@link ASSETTAGS }
     * 
     */
    public ASSETTAGS createASSETTAGS() {
        return new ASSETTAGS();
    }

    /**
     * Create an instance of {@link ASSETGROUPS }
     * 
     */
    public ASSETGROUPS createASSETGROUPS() {
        return new ASSETGROUPS();
    }

    /**
     * Create an instance of {@link VULNINFOLIST }
     * 
     */
    public VULNINFOLIST createVULNINFOLIST() {
        return new VULNINFOLIST();
    }

    /**
     * Create an instance of {@link MWSRC }
     * 
     */
    public MWSRC createMWSRC() {
        return new MWSRC();
    }

    /**
     * Create an instance of {@link MWLIST }
     * 
     */
    public MWLIST createMWLIST() {
        return new MWLIST();
    }

    /**
     * Create an instance of {@link MWINFO }
     * 
     */
    public MWINFO createMWINFO() {
        return new MWINFO();
    }

    /**
     * Create an instance of {@link CUSTOMIZED }
     * 
     */
    public CUSTOMIZED createCUSTOMIZED() {
        return new CUSTOMIZED();
    }

    /**
     * Create an instance of {@link APPENDICES }
     * 
     */
    public APPENDICES createAPPENDICES() {
        return new APPENDICES();
    }

    /**
     * Create an instance of {@link NORESULTS }
     * 
     */
    public NORESULTS createNORESULTS() {
        return new NORESULTS();
    }

    /**
     * Create an instance of {@link ASSETDATAREPORT }
     * 
     */
    public ASSETDATAREPORT createASSETDATAREPORT() {
        return new ASSETDATAREPORT();
    }

    /**
     * Create an instance of {@link HEADER }
     * 
     */
    public HEADER createHEADER() {
        return new HEADER();
    }

    /**
     * Create an instance of {@link TARGET }
     * 
     */
    public TARGET createTARGET() {
        return new TARGET();
    }

    /**
     * Create an instance of {@link USERASSETGROUPS }
     * 
     */
    public USERASSETGROUPS createUSERASSETGROUPS() {
        return new USERASSETGROUPS();
    }

    /**
     * Create an instance of {@link USERIPLIST }
     * 
     */
    public USERIPLIST createUSERIPLIST() {
        return new USERIPLIST();
    }

    /**
     * Create an instance of {@link COMBINEDIPLIST }
     * 
     */
    public COMBINEDIPLIST createCOMBINEDIPLIST() {
        return new COMBINEDIPLIST();
    }

    /**
     * Create an instance of {@link ASSETTAGLIST }
     * 
     */
    public ASSETTAGLIST createASSETTAGLIST() {
        return new ASSETTAGLIST();
    }

    /**
     * Create an instance of {@link EXCLUDEDTAGS }
     * 
     */
    public EXCLUDEDTAGS createEXCLUDEDTAGS() {
        return new EXCLUDEDTAGS();
    }

    /**
     * Create an instance of {@link RISKSCORESUMMARY }
     * 
     */
    public RISKSCORESUMMARY createRISKSCORESUMMARY() {
        return new RISKSCORESUMMARY();
    }

    /**
     * Create an instance of {@link RISKSCOREPERHOST }
     * 
     */
    public RISKSCOREPERHOST createRISKSCOREPERHOST() {
        return new RISKSCOREPERHOST();
    }

    /**
     * Create an instance of {@link HOSTS }
     * 
     */
    public HOSTS createHOSTS() {
        return new HOSTS();
    }

    /**
     * Create an instance of {@link IPADDRESS }
     * 
     */
    public IPADDRESS createIPADDRESS() {
        return new IPADDRESS();
    }

    /**
     * Create an instance of {@link GLOSSARY }
     * 
     */
    public GLOSSARY createGLOSSARY() {
        return new GLOSSARY();
    }

    /**
     * Create an instance of {@link VULNDETAILSLIST }
     * 
     */
    public VULNDETAILSLIST createVULNDETAILSLIST() {
        return new VULNDETAILSLIST();
    }

    /**
     * Create an instance of {@link VULNDETAILS }
     * 
     */
    public VULNDETAILS createVULNDETAILS() {
        return new VULNDETAILS();
    }

    /**
     * Create an instance of {@link COMPLIANCE }
     * 
     */
    public COMPLIANCE createCOMPLIANCE() {
        return new COMPLIANCE();
    }

    /**
     * Create an instance of {@link COMPLIANCEINFO }
     * 
     */
    public COMPLIANCEINFO createCOMPLIANCEINFO() {
        return new COMPLIANCEINFO();
    }

    /**
     * Create an instance of {@link CORRELATION }
     * 
     */
    public CORRELATION createCORRELATION() {
        return new CORRELATION();
    }

    /**
     * Create an instance of {@link EXPLOITABILITY }
     * 
     */
    public EXPLOITABILITY createEXPLOITABILITY() {
        return new EXPLOITABILITY();
    }

    /**
     * Create an instance of {@link EXPLTSRC }
     * 
     */
    public EXPLTSRC createEXPLTSRC() {
        return new EXPLTSRC();
    }

    /**
     * Create an instance of {@link EXPLTLIST }
     * 
     */
    public EXPLTLIST createEXPLTLIST() {
        return new EXPLTLIST();
    }

    /**
     * Create an instance of {@link EXPLT }
     * 
     */
    public EXPLT createEXPLT() {
        return new EXPLT();
    }

    /**
     * Create an instance of {@link MALWARE }
     * 
     */
    public MALWARE createMALWARE() {
        return new MALWARE();
    }

    /**
     * Create an instance of {@link CVSSSCORE }
     * 
     */
    public CVSSSCORE createCVSSSCORE() {
        return new CVSSSCORE();
    }

    /**
     * Create an instance of {@link CVSSBASE }
     * 
     */
    public CVSSBASE createCVSSBASE() {
        return new CVSSBASE();
    }

    /**
     * Create an instance of {@link VENDORREFERENCELIST }
     * 
     */
    public VENDORREFERENCELIST createVENDORREFERENCELIST() {
        return new VENDORREFERENCELIST();
    }

    /**
     * Create an instance of {@link VENDORREFERENCE }
     * 
     */
    public VENDORREFERENCE createVENDORREFERENCE() {
        return new VENDORREFERENCE();
    }

    /**
     * Create an instance of {@link CVEIDLIST }
     * 
     */
    public CVEIDLIST createCVEIDLIST() {
        return new CVEIDLIST();
    }

    /**
     * Create an instance of {@link CVEID }
     * 
     */
    public CVEID createCVEID() {
        return new CVEID();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CUSTOM_SEVERITY")
    public JAXBElement<String> createCUSTOMSEVERITY(String value) {
        return new JAXBElement<String>(_CUSTOMSEVERITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPLIANCE_SECTION")
    public JAXBElement<String> createCOMPLIANCESECTION(String value) {
        return new JAXBElement<String>(_COMPLIANCESECTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SEVERITY")
    public JAXBElement<String> createSEVERITY(String value) {
        return new JAXBElement<String>(_SEVERITY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMPACT")
    public JAXBElement<String> createIMPACT(String value) {
        return new JAXBElement<String>(_IMPACT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DISABLED")
    public JAXBElement<String> createDISABLED(String value) {
        return new JAXBElement<String>(_DISABLED_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "THREAT_COMMENT")
    public JAXBElement<String> createTHREATCOMMENT(String value) {
        return new JAXBElement<String>(_THREATCOMMENT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SECURITY_RISK")
    public JAXBElement<String> createSECURITYRISK(String value) {
        return new JAXBElement<String>(_SECURITYRISK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SRC_NAME")
    public JAXBElement<String> createSRCNAME(String value) {
        return new JAXBElement<String>(_SRCNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FIRST_FOUND")
    public JAXBElement<String> createFIRSTFOUND(String value) {
        return new JAXBElement<String>(_FIRSTFOUND_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OPERATING_SYSTEM")
    public JAXBElement<String> createOPERATINGSYSTEM(String value) {
        return new JAXBElement<String>(_OPERATINGSYSTEM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ID")
    public JAXBElement<String> createID(String value) {
        return new JAXBElement<String>(_ID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OS_CPE")
    public JAXBElement<String> createOSCPE(String value) {
        return new JAXBElement<String>(_OSCPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DNS")
    public JAXBElement<String> createDNS(String value) {
        return new JAXBElement<String>(_DNS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PROTOCOL")
    public JAXBElement<String> createPROTOCOL(String value) {
        return new JAXBElement<String>(_PROTOCOL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TRACKING_METHOD")
    public JAXBElement<String> createTRACKINGMETHOD(String value) {
        return new JAXBElement<String>(_TRACKINGMETHOD_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIMES_FOUND")
    public JAXBElement<String> createTIMESFOUND(String value) {
        return new JAXBElement<String>(_TIMESFOUND_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CVSS_TEMPORAL")
    public JAXBElement<String> createCVSSTEMPORAL(String value) {
        return new JAXBElement<String>(_CVSSTEMPORAL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FQDN")
    public JAXBElement<String> createFQDN(String value) {
        return new JAXBElement<String>(_FQDN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TYPE")
    public JAXBElement<String> createTYPE(String value) {
        return new JAXBElement<String>(_TYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXCLUDED_CATEGORIES")
    public JAXBElement<String> createEXCLUDEDCATEGORIES(String value) {
        return new JAXBElement<String>(_EXCLUDEDCATEGORIES_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ASSET_TAG")
    public JAXBElement<String> createASSETTAG(String value) {
        return new JAXBElement<String>(_ASSETTAG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPANY")
    public JAXBElement<String> createCOMPANY(String value) {
        return new JAXBElement<String>(_COMPANY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SELECTIVE_VULNS")
    public JAXBElement<String> createSELECTIVEVULNS(String value) {
        return new JAXBElement<String>(_SELECTIVEVULNS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPLIANCE_TYPE")
    public JAXBElement<String> createCOMPLIANCETYPE(String value) {
        return new JAXBElement<String>(_COMPLIANCETYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMPLIANCE_DESCRIPTION")
    public JAXBElement<String> createCOMPLIANCEDESCRIPTION(String value) {
        return new JAXBElement<String>(_COMPLIANCEDESCRIPTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MW_ID")
    public JAXBElement<String> createMWID(String value) {
        return new JAXBElement<String>(_MWID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXCLUDED_VULN_LISTS")
    public JAXBElement<String> createEXCLUDEDVULNLISTS(String value) {
        return new JAXBElement<String>(_EXCLUDEDVULNLISTS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MW_LINK")
    public JAXBElement<String> createMWLINK(String value) {
        return new JAXBElement<String>(_MWLINK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LAST_FOUND")
    public JAXBElement<String> createLASTFOUND(String value) {
        return new JAXBElement<String>(_LASTFOUND_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "USERNAME")
    public JAXBElement<String> createUSERNAME(String value) {
        return new JAXBElement<String>(_USERNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOLUTION_COMMENT")
    public JAXBElement<String> createSOLUTIONCOMMENT(String value) {
        return new JAXBElement<String>(_SOLUTIONCOMMENT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VULN_LISTS")
    public JAXBElement<String> createVULNLISTS(String value) {
        return new JAXBElement<String>(_VULNLISTS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CVSS_FINAL")
    public JAXBElement<String> createCVSSFINAL(String value) {
        return new JAXBElement<String>(_CVSSFINAL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MW_PLATFORM")
    public JAXBElement<String> createMWPLATFORM(String value) {
        return new JAXBElement<String>(_MWPLATFORM_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ASSET_GROUP_TITLE")
    public JAXBElement<String> createASSETGROUPTITLE(String value) {
        return new JAXBElement<String>(_ASSETGROUPTITLE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RESULTING_VULNS")
    public JAXBElement<String> createRESULTINGVULNS(String value) {
        return new JAXBElement<String>(_RESULTINGVULNS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GENERATION_DATETIME")
    public JAXBElement<String> createGENERATIONDATETIME(String value) {
        return new JAXBElement<String>(_GENERATIONDATETIME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CATEGORY")
    public JAXBElement<String> createCATEGORY(String value) {
        return new JAXBElement<String>(_CATEGORY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PORT")
    public JAXBElement<String> createPORT(String value) {
        return new JAXBElement<String>(_PORT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "THREAT")
    public JAXBElement<String> createTHREAT(String value) {
        return new JAXBElement<String>(_THREAT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TOTAL_VULNERABILITIES")
    public JAXBElement<String> createTOTALVULNERABILITIES(String value) {
        return new JAXBElement<String>(_TOTALVULNERABILITIES_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LINK")
    public JAXBElement<String> createLINK(String value) {
        return new JAXBElement<String>(_LINK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NETBIOS")
    public JAXBElement<String> createNETBIOS(String value) {
        return new JAXBElement<String>(_NETBIOS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TICKET_STATE")
    public JAXBElement<String> createTICKETSTATE(String value) {
        return new JAXBElement<String>(_TICKETSTATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "URL")
    public JAXBElement<String> createURL(String value) {
        return new JAXBElement<String>(_URL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "REF")
    public JAXBElement<String> createREF(String value) {
        return new JAXBElement<String>(_REF_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MW_ALIAS")
    public JAXBElement<String> createMWALIAS(String value) {
        return new JAXBElement<String>(_MWALIAS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TICKET_NUMBER")
    public JAXBElement<String> createTICKETNUMBER(String value) {
        return new JAXBElement<String>(_TICKETNUMBER_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LAST_UPDATE")
    public JAXBElement<String> createLASTUPDATE(String value) {
        return new JAXBElement<String>(_LASTUPDATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SSL")
    public JAXBElement<String> createSSL(String value) {
        return new JAXBElement<String>(_SSL_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SERVICE")
    public JAXBElement<String> createSERVICE(String value) {
        return new JAXBElement<String>(_SERVICE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOLUTION")
    public JAXBElement<String> createSOLUTION(String value) {
        return new JAXBElement<String>(_SOLUTION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TEMPLATE")
    public JAXBElement<String> createTEMPLATE(String value) {
        return new JAXBElement<String>(_TEMPLATE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MW_TYPE")
    public JAXBElement<String> createMWTYPE(String value) {
        return new JAXBElement<String>(_MWTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PCI_FLAG")
    public JAXBElement<String> createPCIFLAG(String value) {
        return new JAXBElement<String>(_PCIFLAG_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "EXCLUDED_VULNS")
    public JAXBElement<String> createEXCLUDEDVULNS(String value) {
        return new JAXBElement<String>(_EXCLUDEDVULNS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "INSTANCE")
    public JAXBElement<String> createINSTANCE(String value) {
        return new JAXBElement<String>(_INSTANCE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VULN_STATUS")
    public JAXBElement<String> createVULNSTATUS(String value) {
        return new JAXBElement<String>(_VULNSTATUS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FILTER_SUMMARY")
    public JAXBElement<String> createFILTERSUMMARY(String value) {
        return new JAXBElement<String>(_FILTERSUMMARY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BUSINESS_RISK")
    public JAXBElement<String> createBUSINESSRISK(String value) {
        return new JAXBElement<String>(_BUSINESSRISK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AVG_SECURITY_RISK")
    public JAXBElement<String> createAVGSECURITYRISK(String value) {
        return new JAXBElement<String>(_AVGSECURITYRISK_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "START")
    public JAXBElement<String> createSTART(String value) {
        return new JAXBElement<String>(_START_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MW_RATING")
    public JAXBElement<String> createMWRATING(String value) {
        return new JAXBElement<String>(_MWRATING_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IMPACT_COMMENT")
    public JAXBElement<String> createIMPACTCOMMENT(String value) {
        return new JAXBElement<String>(_IMPACTCOMMENT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DESC")
    public JAXBElement<String> createDESC(String value) {
        return new JAXBElement<String>(_DESC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "END")
    public JAXBElement<String> createEND(String value) {
        return new JAXBElement<String>(_END_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TITLE")
    public JAXBElement<String> createTITLE(String value) {
        return new JAXBElement<String>(_TITLE_QNAME, String.class, null, value);
    }

}
