//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TOTAL_VULNERABILITIES"/>
 *         &lt;element ref="{}AVG_SECURITY_RISK"/>
 *         &lt;element ref="{}BUSINESS_RISK"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "totalvulnerabilities",
    "avgsecurityrisk",
    "businessrisk"
})
@XmlRootElement(name = "RISK_SCORE_SUMMARY")
public class RISKSCORESUMMARY {

    @XmlElement(name = "TOTAL_VULNERABILITIES", required = true)
    protected String totalvulnerabilities;
    @XmlElement(name = "AVG_SECURITY_RISK", required = true)
    protected String avgsecurityrisk;
    @XmlElement(name = "BUSINESS_RISK", required = true)
    protected String businessrisk;

    /**
     * Gets the value of the totalvulnerabilities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALVULNERABILITIES() {
        return totalvulnerabilities;
    }

    /**
     * Sets the value of the totalvulnerabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALVULNERABILITIES(String value) {
        this.totalvulnerabilities = value;
    }

    /**
     * Gets the value of the avgsecurityrisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAVGSECURITYRISK() {
        return avgsecurityrisk;
    }

    /**
     * Sets the value of the avgsecurityrisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAVGSECURITYRISK(String value) {
        this.avgsecurityrisk = value;
    }

    /**
     * Gets the value of the businessrisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBUSINESSRISK() {
        return businessrisk;
    }

    /**
     * Sets the value of the businessrisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBUSINESSRISK(String value) {
        this.businessrisk = value;
    }

}
