//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}VULN_LISTS" minOccurs="0"/>
 *         &lt;element ref="{}SELECTIVE_VULNS" minOccurs="0"/>
 *         &lt;element ref="{}EXCLUDED_VULN_LISTS" minOccurs="0"/>
 *         &lt;element ref="{}EXCLUDED_VULNS" minOccurs="0"/>
 *         &lt;element ref="{}RESULTING_VULNS" minOccurs="0"/>
 *         &lt;element ref="{}FILTER_SUMMARY" minOccurs="0"/>
 *         &lt;element ref="{}EXCLUDED_CATEGORIES" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vulnlists",
    "selectivevulns",
    "excludedvulnlists",
    "excludedvulns",
    "resultingvulns",
    "filtersummary",
    "excludedcategories"
})
@XmlRootElement(name = "TEMPLATE_DETAILS")
public class TEMPLATEDETAILS {

    @XmlElement(name = "VULN_LISTS")
    protected String vulnlists;
    @XmlElement(name = "SELECTIVE_VULNS")
    protected String selectivevulns;
    @XmlElement(name = "EXCLUDED_VULN_LISTS")
    protected String excludedvulnlists;
    @XmlElement(name = "EXCLUDED_VULNS")
    protected String excludedvulns;
    @XmlElement(name = "RESULTING_VULNS")
    protected String resultingvulns;
    @XmlElement(name = "FILTER_SUMMARY")
    protected String filtersummary;
    @XmlElement(name = "EXCLUDED_CATEGORIES")
    protected String excludedcategories;

    /**
     * Gets the value of the vulnlists property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVULNLISTS() {
        return vulnlists;
    }

    /**
     * Sets the value of the vulnlists property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVULNLISTS(String value) {
        this.vulnlists = value;
    }

    /**
     * Gets the value of the selectivevulns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSELECTIVEVULNS() {
        return selectivevulns;
    }

    /**
     * Sets the value of the selectivevulns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSELECTIVEVULNS(String value) {
        this.selectivevulns = value;
    }

    /**
     * Gets the value of the excludedvulnlists property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXCLUDEDVULNLISTS() {
        return excludedvulnlists;
    }

    /**
     * Sets the value of the excludedvulnlists property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXCLUDEDVULNLISTS(String value) {
        this.excludedvulnlists = value;
    }

    /**
     * Gets the value of the excludedvulns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXCLUDEDVULNS() {
        return excludedvulns;
    }

    /**
     * Sets the value of the excludedvulns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXCLUDEDVULNS(String value) {
        this.excludedvulns = value;
    }

    /**
     * Gets the value of the resultingvulns property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESULTINGVULNS() {
        return resultingvulns;
    }

    /**
     * Sets the value of the resultingvulns property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESULTINGVULNS(String value) {
        this.resultingvulns = value;
    }

    /**
     * Gets the value of the filtersummary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILTERSUMMARY() {
        return filtersummary;
    }

    /**
     * Sets the value of the filtersummary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILTERSUMMARY(String value) {
        this.filtersummary = value;
    }

    /**
     * Gets the value of the excludedcategories property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXCLUDEDCATEGORIES() {
        return excludedcategories;
    }

    /**
     * Sets the value of the excludedcategories property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXCLUDEDCATEGORIES(String value) {
        this.excludedcategories = value;
    }

}
