//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.02 at 10:44:13 AM EDT 
//
/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.qualys.audit.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}QID"/>
 *         &lt;element ref="{}TYPE"/>
 *         &lt;element ref="{}PORT" minOccurs="0"/>
 *         &lt;element ref="{}SERVICE" minOccurs="0"/>
 *         &lt;element ref="{}FQDN" minOccurs="0"/>
 *         &lt;element ref="{}PROTOCOL" minOccurs="0"/>
 *         &lt;element ref="{}SSL" minOccurs="0"/>
 *         &lt;element ref="{}INSTANCE" minOccurs="0"/>
 *         &lt;element ref="{}RESULT" minOccurs="0"/>
 *         &lt;element ref="{}FIRST_FOUND" minOccurs="0"/>
 *         &lt;element ref="{}LAST_FOUND" minOccurs="0"/>
 *         &lt;element ref="{}TIMES_FOUND" minOccurs="0"/>
 *         &lt;element ref="{}VULN_STATUS" minOccurs="0"/>
 *         &lt;element ref="{}CVSS_FINAL" minOccurs="0"/>
 *         &lt;element ref="{}TICKET_NUMBER" minOccurs="0"/>
 *         &lt;element ref="{}TICKET_STATE" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "qid",
    "type",
    "port",
    "service",
    "fqdn",
    "protocol",
    "ssl",
    "instance",
    "result",
    "firstfound",
    "lastfound",
    "timesfound",
    "vulnstatus",
    "cvssfinal",
    "ticketnumber",
    "ticketstate"
})
@XmlRootElement(name = "VULN_INFO")
public class VULNINFO {

    @XmlElement(name = "QID", required = true)
    protected QID qid;
    @XmlElement(name = "TYPE", required = true)
    protected String type;
    @XmlElement(name = "PORT")
    protected String port;
    @XmlElement(name = "SERVICE")
    protected String service;
    @XmlElement(name = "FQDN")
    protected String fqdn;
    @XmlElement(name = "PROTOCOL")
    protected String protocol;
    @XmlElement(name = "SSL")
    protected String ssl;
    @XmlElement(name = "INSTANCE")
    protected String instance;
    @XmlElement(name = "RESULT")
    protected RESULT result;
    @XmlElement(name = "FIRST_FOUND")
    protected String firstfound;
    @XmlElement(name = "LAST_FOUND")
    protected String lastfound;
    @XmlElement(name = "TIMES_FOUND")
    protected String timesfound;
    @XmlElement(name = "VULN_STATUS")
    protected String vulnstatus;
    @XmlElement(name = "CVSS_FINAL")
    protected String cvssfinal;
    @XmlElement(name = "TICKET_NUMBER")
    protected String ticketnumber;
    @XmlElement(name = "TICKET_STATE")
    protected String ticketstate;

    /**
     * Gets the value of the qid property.
     * 
     * @return
     *     possible object is
     *     {@link QID }
     *     
     */
    public QID getQID() {
        return qid;
    }

    /**
     * Sets the value of the qid property.
     * 
     * @param value
     *     allowed object is
     *     {@link QID }
     *     
     */
    public void setQID(QID value) {
        this.qid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTYPE() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTYPE(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPORT() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPORT(String value) {
        this.port = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERVICE() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERVICE(String value) {
        this.service = value;
    }

    /**
     * Gets the value of the fqdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFQDN() {
        return fqdn;
    }

    /**
     * Sets the value of the fqdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFQDN(String value) {
        this.fqdn = value;
    }

    /**
     * Gets the value of the protocol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROTOCOL() {
        return protocol;
    }

    /**
     * Sets the value of the protocol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROTOCOL(String value) {
        this.protocol = value;
    }

    /**
     * Gets the value of the ssl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSL() {
        return ssl;
    }

    /**
     * Sets the value of the ssl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSL(String value) {
        this.ssl = value;
    }

    /**
     * Gets the value of the instance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINSTANCE() {
        return instance;
    }

    /**
     * Sets the value of the instance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINSTANCE(String value) {
        this.instance = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link RESULT }
     *     
     */
    public RESULT getRESULT() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link RESULT }
     *     
     */
    public void setRESULT(RESULT value) {
        this.result = value;
    }

    /**
     * Gets the value of the firstfound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTFOUND() {
        return firstfound;
    }

    /**
     * Sets the value of the firstfound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTFOUND(String value) {
        this.firstfound = value;
    }

    /**
     * Gets the value of the lastfound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTFOUND() {
        return lastfound;
    }

    /**
     * Sets the value of the lastfound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTFOUND(String value) {
        this.lastfound = value;
    }

    /**
     * Gets the value of the timesfound property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIMESFOUND() {
        return timesfound;
    }

    /**
     * Sets the value of the timesfound property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIMESFOUND(String value) {
        this.timesfound = value;
    }

    /**
     * Gets the value of the vulnstatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVULNSTATUS() {
        return vulnstatus;
    }

    /**
     * Sets the value of the vulnstatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVULNSTATUS(String value) {
        this.vulnstatus = value;
    }

    /**
     * Gets the value of the cvssfinal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCVSSFINAL() {
        return cvssfinal;
    }

    /**
     * Sets the value of the cvssfinal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCVSSFINAL(String value) {
        this.cvssfinal = value;
    }

    /**
     * Gets the value of the ticketnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTICKETNUMBER() {
        return ticketnumber;
    }

    /**
     * Sets the value of the ticketnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTICKETNUMBER(String value) {
        this.ticketnumber = value;
    }

    /**
     * Gets the value of the ticketstate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTICKETSTATE() {
        return ticketstate;
    }

    /**
     * Sets the value of the ticketstate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTICKETSTATE(String value) {
        this.ticketstate = value;
    }

}
